### PR TITLE
Add license disclaimers

### PR DESCRIPTION
**Pull request by marvinschopf**
I've added some license disclaimers for all dependencies of this project and all dependencies of the dependencies of this project. Thank you. @jens1o

### CODE REVIEW

**Comment by jens1o** [comment]
How did you created this?

**Comment by marvinschopf** [comment]
@jens1o I created the file using the following command:
```bash
yarn licenses generate-disclaimer > ACKNOWLEDGEMENTS
```

**Comment by jens1o** [comment]
Is it possible to specify one protocol for cloning? It looks like it's selecting `https://` or `git:// / ssh://` randomly. I would like it if it would be possible to use one constantly.

**Comment by marvinschopf** [comment]
You mean the specified source url in the acknowledgements file?
`yarn` reads that url from the project's package.json's `repository` field.

**Comment by jens1o** [comment]
> You mean the specified source url in the acknowledgements file?

Yeah, that's it.

**Comment by marvinschopf** [comment]
Do you think, we can merge this PR now?

**Comment by jens1o** [comment]
Could you answer my question first please? When it isn't possible right now, I will accept it, but I think it would be better if it would be more consistent. :)

**Comment by marvinschopf** [comment]
Yes, sure: We could manually change the protocols, but if we want to have that automated, we should leave it as it is.

**Comment by jens1o** [comment]
> but if we want to have that automated, we should leave it as it is.

Yeah, good point.

**Review by jens1o — APPROVED** [review]

**Comment by marvinschopf** [comment]
Thank you :)

**Comment by marvinschopf** [comment]
I will merge it now.

**Pull request merged**
