### PR TITLE
Add ci configs

### PR DESCRIPTION
**Pull request by marvinschopf**
Hello.
I've added a config for travis, only to do syntax checks and such things.

I think, it's no problem to merge it.

Thank you @jens1o 
:)

### CODE REVIEW

**Comment by jens1o** [comment]
Could you add greenkeeper? Why do you want to build on mac and linux?

**Comment by marvinschopf** [comment]
I can't add Greenkeeper, because the organization owner needs to add it, i think. But I will try it.

I'm building on both Linux and MacOS, to check Cross-Platform-Compatibility? Should I remove mac?

Thank you for replying 👍 👍 👍

**Comment by jens1o** [comment]
There should be no differences as we have no different handlings for different operating systems, but okay.

**Comment by marvinschopf** [comment]
So I can leave OSX in the config?

**Comment by jens1o** [comment]
Yeah.

**Comment by marvinschopf** [comment]
Thank you.

**Comment by marvinschopf** [comment]
What should be done before this can be merged?

**Review by jens1o — APPROVED** [review]

**Comment by jens1o** [comment]
I was just waiting for the checks to complete.

**Comment by marvinschopf** [comment]
:)

**Pull request merged**
