### PR TITLE
completly refactored import process to be more dynamic

### PR DESCRIPTION
**Pull request by jens1o**
feel free to try it out and let me know what you think :)

### CODE REVIEW

**Review by marvinschopf — APPROVED** [review]
That's REALLY cool!

**Comment by jens1o** [comment]
@MagicMarvMan Did you tested / reviewed it?

**Comment by marvinschopf** [comment]
No, I hadn't had time to test it. But it looks cool, generally. I will test it now. Sorry for the circumstances.

**Comment by jens1o** [comment]
No problem at all, take your time :)

**Review by marvinschopf — APPROVED** [review]
Works like a charm, good job!

**Comment by jens1o** [comment]
Thank you :)

**Pull request merged**
